targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    import: "package:json_component_generator/json_component_generator.dart"
    builder_factories: ["generateJsonComponent"]
    build_extensions: { ".dart": [".json_component.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable|json_serializable"]